### DISCUSSION TITLE
[Help]: Cannot access webpage portal after container startup

### DISCUSSION THREAD

**Discussion by mataborg** [mbentley/docker-omada-controller#498] [Help] [answered]
### Controller Version

5.14.32.3

### Describe Your Issue or Question

Cannot access portal webpage by IP:port after container creation. Logs seem to indicate the container is functioning normally.

### Expected Behavior

Access web server at https://<>:8843 or http://<>:8088

### Steps to Reproduce

Launch container in portainer EE using compose as a stack in Docker Swarm. Tried decalring the host network explicitly and just by port assignments. 

### How You're Launching the Container

```plain
---
version: '3.8'

services:
  omada:
    image: mbentley/omada-controller:latest-chromium
    ulimits:
      nofile:
        soft: 4096
        hard: 8192
    stop_grace_period: 30s
    environment:
      - PUID=12001
      - PGID=12000
      - MANAGE_HTTP_PORT=8088
      - MANAGE_HTTPS_PORT=8043
      - PORTAL_HTTP_PORT=8088
      - PORTAL_HTTPS_PORT=8843
      - PORT_APP_DISCOVERY=27001
      - PORT_ADOPT_V1=29812
      - PORT_UPGRADE_V1=29813
      - PORT_MANAGER_V1=29811
      - PORT_MANAGER_V2=29814
      - PORT_DISCOVERY=29810
      - PORT_TRANSFER_V2=29815
      - PORT_RTTY=29816
      - SHOW_SERVER_LOGS=true
      - SHOW_MONGODB_LOGS=false
      - SSL_CERT_NAME=tls.crt
      - SSL_KEY_NAME=tls.key
      - TZ=America/Boise
    volumes:
      - omada-data:/opt/tplink/EAPController/data
      - omada-logs:/opt/tplink/EAPController/logs

volumes:
  omada-data:
  omada-logs:
```

### Container Logs

```plain
will attach later due to github dumping new discussion because of log size
```

### MongoDB Logs

```plain
will attach later due to github dumping new discussion because of log size
```

**Comment by mataborg** [comment]
[mongod.log](https://github.com/user-attachments/files/17692738/mongod.log)
[nsx7vuey64mtfhwxpiu9pc8an_logs.txt](https://github.com/user-attachments/files/17692740/nsx7vuey64mtfhwxpiu9pc8an_logs.txt)

**Comment by mataborg** [comment]
Welp, on a hunch I started modifying the compose file to expose the following ports since host binding didn't seem to do the trick:
8088:8088
8043:8043
8843:8843

And the web portal finally popped up at port 8043. Not sure if this is expected behavior due to being deployed as part of a swarm?
Either way, I may recommend adding explicit ports to the default docker compose file:
```
version: "3.1"

services:
  omada-controller:
    container_name: omada-controller
    image: mbentley/omada-controller:5.14
    restart: unless-stopped
    ulimits:
      nofile:
        soft: 4096
        hard: 8192
    stop_grace_period: 60s
    network_mode: host
    environment:
      - PUID=508
      - PGID=508
      - MANAGE_HTTP_PORT=8088
      - MANAGE_HTTPS_PORT=8043
      - PORTAL_HTTP_PORT=8088
      - PORTAL_HTTPS_PORT=8843
      - PORT_APP_DISCOVERY=27001
      - PORT_ADOPT_V1=29812
      - PORT_UPGRADE_V1=29813
      - PORT_MANAGER_V1=29811
      - PORT_MANAGER_V2=29814
      - PORT_DISCOVERY=29810
      - PORT_TRANSFER_V2=29815
      - PORT_RTTY=29816
      - SHOW_SERVER_LOGS=true
      - SHOW_MONGODB_LOGS=false
      - SSL_CERT_NAME=tls.crt
      - SSL_KEY_NAME=tls.key
      - TZ=Etc/UTC
    volumes:
      - omada-data:/opt/tplink/EAPController/data
      - omada-logs:/opt/tplink/EAPController/logs
    **ports:
      - 8088:8088
      - 8843:8843
      - 8043:8043
      - 27001:27001
      - 19810:19810
      - 29810:29810
      - 29811:29811
      - 29812:29812
      - 29813:29813
      - 29814:29814
      - 29815:29815
      - 29816:29816**

volumes:
  omada-data:
  omada-logs:
```
