### DISCUSSION TITLE
[Help]: After 5.15.20.16 controller is always redirecting to https

### DISCUSSION THREAD

**Discussion by tokenize47** [mbentley/docker-omada-controller#557] [Help]
### Controller Version

5.15.20.16

### Describe Your Issue or Question

The title says all. I've always used http to access the controller page in my LAN. After the update to 5.15.20.16 it always redirects to https. It's not really an issue, but a bit annoying that I have to accept the security exception and I'm curious what could have changed.

### Expected Behavior

No https redirection

### Steps to Reproduce

Open your controller url with http://ip:http_port and watch it being auto redirected to https://ip:https_port

### How You're Launching the Container

```plain
docker run -d \
  --name=omada \
  --stop-timeout 60 \
  --restart=unless-stopped \
  --net=host \
  --ulimit nofile=4096:8192 \
  -e TZ=****\
  -v ****:/opt/tplink/EAPController/data \
  -v ****:/opt/tplink/EAPController/logs \
  mbentley/omada-controller
```

### Container Logs

```plain
Not applicable
```

### Additional Context

Not really an issue, but it's intriguing and annoying

**Comment by tokenize47** [comment]
I just noticed in the beta changelog that they forced this. I don't see any need for this in a local network, so is there any way to disable it?

**Reply by pixielark** [reply]
I have the same issue

**Comment by mbentley** [comment]
I would say that your best bet is to complain on the [TP-Link forums](https://community.tp-link.com/en/business/forum/582).  When they blocked being able to use ports 1-1024, I stated my case and they reversed their change so it's worth a shot.  I don't see why they wouldn't default to not allowing http but still have the toggle.

**Comment by sofiaurora270** [comment]
I added a threaf about this: https://community.tp-link.com/en/business/forum/topic/782912?page=1

**Comment by srwareham** [comment]
Just to consolidate some of the information above:
TP-Link published [SDN Controller V5.15.20.X](https://community.tp-link.com/en/business/forum/topic/745920). Within the release notes they have "Bugs Fixed: Reduced potential security risks by forcibly redirecting HTTP requests and responses to HTTPS ones." This change seems to ignore the "Redirect HTTP to HTTPS" setting that is still present... This effectively means you can no longer do your own SSL termination by reverse proxying to an HTTP service.

sofiaurora created this [community forum request](https://community.tp-link.com/en/business/forum/topic/782912?page=1) to revert the change. You can upvote/comment to try to show TP-Link this is not a good change.

In the meantime, running the older release with `image: mbentley/omada-controller:5.15.20.16` will still work with HTTP.

**Comment by tokenize47** [comment]
The option "Redirect HTTP to HTTPS" applies to the Portal only, not the controller. They effectively hard coded this change.

**Comment by sofiaurora270** [comment]
In the meantime, i've now added "--serverstransport.insecureskipverify=true" to my traefik configuration, and forwarded requests to 8043 port. Not happy about the change, but at least it wasn't that hard to overcome.

**Comment by CyberAustin** [comment]
Anyone got a proven method for the ServersTransport on kubernetes Ingress or IngressRoute? I'm striking out here after 3 days of trying.

**Reply by sofiaurora270** [reply]
Im using traefik, installed via helm, so i added this in to my traefik helm values.yaml

```
additionalArguments:
  - "--serverstransport.insecureskipverify=true"
```

**Reply by sofiaurora270** [reply]
Not sure if this is needed/relevant, but here is my ports config:

```
# redirect all http to https
ports:
  web:
    redirections:
      entryPoint:
        to: websecure
        scheme: https
        permanent: true
    forwardedHeaders:
      insecure: true
  websecure:
    http3:
      enabled: true
      advertisedPort: 443
    forwardedHeaders:
      insecure: true
    transport:                                # Try to fix nextcloud sync problems
      respondingTimeouts:
        readTimeout: 30m
        writeTimeout: 30m
        idleTimeout: 3m
```
