### ISSUE TITLE
Latest docker image 3.2 seems broken

### ISSUE THREAD

**Issue by dsteinkopf** [mbentley/docker-omada-controller#112]
**Describe the bug**
Pulling and running `mbentley/omada-controller:3.2` has been working fine for months (or years). Since today I keep getting an error: `ERROR: for omada_omada_1  Cannot start service omada: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "/entrypoint.sh": stat /entrypoint.sh: no such file or directory: unknown`

Cloneing this repo and building the image myself works:
```
git clone https://github.com/mbentley/docker-omada-controller
docker build -f Dockerfile.v3.2.x -t mbentley/omada-controller:3.2dirk .
```

**To Reproduce**

I am using a compose file but the problem should exist in any way you try to start the container.

**Expected behavior**
COontainer starts normally.

**How you're launching your container**
```
version: '2.1'
services:
  omada:
    build: .
    environment:
      - TZ=Europe/Berlin
      - SMALL_FILES=true
    ports:
      - ${BIND_IP}:8088:8088
      - ${BIND_IP}:8043:8043
      - ${BIND_IP}:27001:27001/udp
      - ${BIND_IP}:27002:27002
      - ${BIND_IP}:29810:29810/udp
      - ${BIND_IP}:29811:29811
      - ${BIND_IP}:29812:29812
      - ${BIND_IP}:29813:29813
    restart: unless-stopped
    volumes:
      - ${OMADA_DATA_DIR:?err}/data:/opt/tplink/EAPController/data
      - ${OMADA_DATA_DIR:?err}/work:/opt/tplink/EAPController/work
      - ${OMADA_DATA_DIR:?err}/logs:/opt/tplink/EAPController/logs
      - ${OMADA_DATA_DIR:?err}/backup:/opt/tplink/EAPController/backup
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
```

Dockerfile:
```
FROM mbentley/omada-controller:3.2dirk
# upgrade to 4.1 will make EAP110 V1.0/2.0 incompatible
# add mongo client for backup
RUN \
    apt-get update && \
    apt-get install -y \
        mongodb-clients
```

**Container Logs**
Starting the container fails with this error:
```
ERROR: for omada_omada_1  Cannot start service omada: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "/entrypoint.sh": stat /entrypoint.sh: no such file or directory: unknown
```

**Additional context**
Thank you :-)
