### ISSUE TITLE
Running docker compose by stack in portainer results in "fail to start mongodb server"

### ISSUE THREAD

**Issue by luvxinh** [mbentley/docker-omada-controller#179]
**Environment:
- Browser: Firefox latest as at the date of writing this.
- openmediavault v6. Storage is created on a external hdd.
- Portainer latest installed by openmediavault.
- Docker latest installed by openmediavault.
- Docker swarm including 2 nodes of Raspberry pi 4.

**Describe the bug**

I use the docker compose file to deploy a stack on Portainer but it does not spin up. It retried for several times, eventually got stopped, then Portainer deploy another stack, but the same thing happen.

**To Reproduce**

Using the above environment and follow the normal deploy process of a stack in Portainer.

**Expected behavior**
The mongodb should launch, and omada controller should be launched.

**How you're launching your container**

copy and paste the below in the stack deployment of Portainer.

```
version: "3.1"

services:
   omada-controller:
     container_name: omada-controller
     image: mbentley/omada-controller:latest
     environment:
      - TZ=Etc/UTC
      - MANAGE_HTTP_PORT=8088
      - MANAGE_HTTPS_PORT=8043
      - PORTAL_HTTP_PORT=8088
      - PORTAL_HTTPS_PORT=8043
      - SHOW_SERVER_LOGS=true
      - SHOW_MONGODB_LOGS=false
      - SSL_CERT_NAME="tls.crt"
      - SSL_KEY_NAME="tls.key"
     network_mode: host

     volumes:
      - /srv/dev-disk-by-uuid-9E900A70900A4F69/omada/data:/opt/tplink/EAPController/data
      - /srv/dev-disk-by-uuid-9E900A70900A4F69/omada/work:/opt/tplink/EAPController/work
      - /srv/dev-disk-by-uuid-9E900A70900A4F69/omada/logs:/opt/tplink/EAPController/logs
     restart: unless-stopped
#volumes:
#  omada-data:
#  omada-work:
#  omada-logs:
```

**Container Logs**

[mongod.txt](https://github.com/mbentley/docker-omada-controller/files/8043329/mongod.txt)
[server.txt](https://github.com/mbentley/docker-omada-controller/files/8043330/server.txt)

**Additional context**
I have checked and the storage set by openmediavault is accessible.
![image](https://user-images.githubusercontent.com/33537323/153471235-05543f29-874d-4569-994d-3916042e0732.png)
