### ISSUE TITLE
[Feature]: Allow custom startup script/ check for existence of file

### ISSUE THREAD

**Issue by tophee** [mbentley/docker-omada-controller#343]
### What problem are you looking to solve?

The volumes mounted into my omada controller are hosted on another machine and need to be mounted on the docker host before the container can run. When everything works fine, then this happens long before the container is launched and there is no problem. But in an imperfect world, it happens that the remote file system doesn't mount properly and in that case, the container will create a new install at the mountpoint. 

I would, however, prefer it to shut down with an error message.

### Describe the solution that you have in mind

My idea would be to create a file on the remote file system and have a startup script check for that file. If it does not exist, it means the file system is not mounted and the script would then shut down the container.

GPT-4 explained to me that such a startup script would need to be backed into the image and hence I am asking here whether you could add support for such a custom script.

### Additional Context

I am formulating the request in terms of a user-definable startup script so that multiple use cases can be covered, but I can see how that may generate unnecessary support requests so that I would be perfectly fine with a more narrow feature that checks for the existence of a file executes a script if it doesn't exist.  

This may not be a very common issue and perhaps there are better ways of solving this (this is too low level for me, so I can't tell), but I'm submitting the idea here to see if it makes any sense ;-)

**Comment by mbentley** [comment]
Just curious - how are you starting your container?  With a `docker run`?  Using `compose`?  Something else?  There might be a better way to handle this.

One thing I do is that I start my containers using a bit of bash script wrapper that just calls some `docker run` commands.  With that, I use the `--mount` syntax for volumes instead of the `-v` syntax.  One of the benefits is that if my filesystem is not mounted, the container will fail to start.

For example, here is my run command:

```
docker run -d \
  --init \
  --name omada-controller \
  --no-healthcheck \
  --hostname omada \
  --network macvlan1 \
  --ip 192.168.2.160 \
  --restart unless-stopped \
  --sysctl net.ipv4.ip_unprivileged_port_start=0 \
  --ulimit nofile=4096:8192 \
  -e TZ="America/Indiana/Indianapolis" \
  -e MANAGE_HTTP_PORT=80 \
  -e MANAGE_HTTPS_PORT=443 \
  -e PORTAL_HTTP_PORT=8088 \
  -e PORTAL_HTTPS_PORT=8843 \
  --mount type=bind,source=/zfs/apps/omada-controller/data,destination=/opt/tplink/EAPController/data,readonly=false \
  --mount type=bind,source=/zfs/apps/omada-controller/logs,destination=/opt/tplink/EAPController/logs,readonly=false \
  --mount type=bind,source=/zfs/apps/omada-controller/cert,destination=/cert,readonly=true \
  --cpus 2 \
  --memory 4g \
  --memory-swap 5g \
  mbentley/omada-controller:5.12
```

My filesystem is mounted at `/zfs/apps/omada-controller` (it's zfs if you couldn't tell) and the thing about the `--mount` flag is that it will not create the directory if it does not exist, unlike the `-v` flag.  For example:

```
# docker run -it --rm --mount type=bind,source=/tmp/thisisnotreal,destination=/data alpine
docker: Error response from daemon: invalid mount config for type "bind": bind source path does not exist: /tmp/thisisnotreal.
See 'docker run --help'.
```


Good news is that the same thing can be done with compose, for example:

```
version: "3.8"
services:
  web:
    image: nginx:alpine
    volumes:
      - type: bind
        source: ./doesnotexist
        target: /data
```

```
$ docker-compose up
[+] Running 0/0
 ⠋ Container composetest-web-1  Creating                                                                                                                     0.0s
Error response from daemon: invalid mount config for type "bind": bind source path does not exist: /host_mnt/Users/mbentley/temp/composetest/doesnotexist
```

**Comment by tophee** [comment]
Oh, nice! Great to see that there is an easier solution for this.

I'm using portainer stacks, so your docker compose solution should work (not sure whether Portainer actually uses docker compose or something else, but so far all docker-compos files I threw at it as a stack worked just fine.

This is my docker-compose/stack
````
version: '2.2'

services:
  omada:
    image: mbentley/omada-controller:latest
    restart: unless-stopped
    container_name: omada-controller
    network_mode: host
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - "/iscsimnt/omada/data:/opt/tplink/EAPController/data"
      - "/iscsimnt/omada/work:/opt/tplink/EAPController/work"
      - "/iscsimnt/omada/logs:/opt/tplink/EAPController/logs"
    environment:
      - MANAGE_HTTP_PORT=9088
      - MANAGE_HTTPS_PORT=8043
      - PORTAL_HTTP_PORT:=9088
      - PORTAL_HTTPS_PORT=8843
      - SHOW_SERVER_LOGS=true
      - SHOW_MONGODB_LOGS=true
      - TZ=Europe/Stockholm
````

So, let's see how that will translate to bind mounts...

````
version: '2.2'

services:
  omada:
    image: mbentley/omada-controller:latest
    restart: unless-stopped
    container_name: omada-controller
    network_mode: host
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - type: bind
        source: /iscsimnt/omada/data
        target: /opt/tplink/EAPController/data
      - type: bind
        source: /iscsimnt/omada/work
        target: /opt/tplink/EAPController/work
      - type: bind
        source: /iscsimnt/omada/logs
        target: /opt/tplink/EAPController/logs

    environment:
      - MANAGE_HTTP_PORT=9088
      - MANAGE_HTTPS_PORT=8043
      - PORTAL_HTTP_PORT:=9088
      - PORTAL_HTTPS_PORT=8843
      - SHOW_SERVER_LOGS=true
      - SHOW_MONGODB_LOGS=true
      - TZ=Europe/Stockholm
````

Will try it out!
