### ISSUE TITLE
Discovery requires network_mode: host

### ISSUE THREAD

**Issue by Javerre** [mbentley/docker-omada-controller#45]
Hi, 

I've just pulled de2206826ae4 and created an application with the following docker-compose settings:

```
version: '3'
networks:
  omada_net:
services:
  omada:
    container_name: omada
    image: mbentley/omada-controller:latest
    networks:
      - omada_net
    ports:
      - '8088:8088'
      - '8043:8043'
      - '27001:27001/udp'
      - '27002:27002'
      - '27217:27217'
      - '29810:29810/udp'
      - '29811:29811'
      - '29812:29812'
      - '29813:29813'
    volumes:
      - /share/Container/Omada/data:/opt/tplink/EAPController/data
      - /share/Container/Omada/work:/opt/tplink/EAPController/work
      - /share/Container/Omada/logs:/opt/tplink/EAPController/logs
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
```

This can run, connect to the web, register with the TP-Link cloud service, etc. but does **not detect my EAP devices**. Checking the logs, it appears that MongoDB is not starting.

If instead I use the following docker-compose file:

```
version: '3'
services:
  omada:
    network_mode: host
    container_name: omada
    image: mbentley/omada-controller:latest
    volumes:
      - /share/Container/Omada/data:/opt/tplink/EAPController/data
      - /share/Container/Omada/work:/opt/tplink/EAPController/work
      - /share/Container/Omada/logs:/opt/tplink/EAPController/logs
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
```

everything works as expected, MongoDB starts and Omada detects my EAP devices fine.
