### ISSUE TITLE
[Bug]: Unable to bind to cloud

### ISSUE THREAD

**Issue by ilexpl01** [mbentley/docker-omada-controller#565]
### Controller Version

5.15.20.18

### Describe the Bug

Running docker version.

Below my compose file:

```
version: "3.1"

services:
  omada-controller:
    container_name: omada-controller
    image: mbentley/omada-controller:latest
    restart: unless-stopped
    ulimits:
      nofile:
        soft: 4096
        hard: 8192
    stop_grace_period: 60s
    network_mode: host
    environment:
      - PUID=508
      - PGID=508
      - MANAGE_HTTP_PORT=8088
      - MANAGE_HTTPS_PORT=8043
      - PORTAL_HTTP_PORT=8088
      - PORTAL_HTTPS_PORT=8843
      - PORT_APP_DISCOVERY=27001
      - PORT_ADOPT_V1=29812
      - PORT_UPGRADE_V1=29813
      - PORT_MANAGER_V1=29811
      - PORT_MANAGER_V2=29814
      - PORT_DISCOVERY=29810
      - PORT_TRANSFER_V2=29815
      - PORT_RTTY=29816
      - SHOW_SERVER_LOGS=true
      - SHOW_MONGODB_LOGS=false

    volumes:
      - /volume1/docker/omada-controller/omada-data:/opt/tplink/EAPController/data:rw
      - /volume1/docker/omada-controller/omada-logs:/opt/tplink/EAPController/logs:rw
      - /volume1/docker/localtime:/etc/localtime:ro
      - /volume1/docker/timezone:/etc/timezone:ro

``` 

I get the following error:

![Image](https://github.com/user-attachments/assets/064a827f-ae29-4bc5-8538-3999149b343f)

I also see the multiple errors in my log:

04-02-2025 20:39:12.846 INFO [client-inform-work-group-2] [] c.t.s.o.c.p.c.k(): com.tplink.smb.omada.client.port.cache.k$b: Lan network does not exist, OmadacId: cc966a046a1aedcd418248d7afa1655a, SiteId: 66158081904515713df785cb, vid:0

04-02-2025 20:39:15.592 INFO [Thread-9] [] c.t.e.c.c.q(): set connection status: DISCONNECTED_NORMAL

04-02-2025 20:39:42.959 INFO [client-inform-work-group-0] [] c.t.s.o.c.p.c.k(): com.tplink.smb.omada.client.port.cache.k$b: Lan network does not exist, OmadacId: cc966a046a1aedcd418248d7afa1655a, SiteId: 66158081904515713df785cb, vid:0

Not sure if related to my problem.

### Expected Behavior

connect to TP-Link cloud service

### Steps to Reproduce

....

### How You're Launching the Container

```plain
....
```

### Container Logs

```plain
...
```

### MongoDB Logs

```plain
...
```
